name: tgswitch
version: '0.12.04'
summary: A command line tool to switch between different versions of terragrunt
description: |
  The `tgswitch` command line tool lets you switch between different versions of terragrunt(https://www.terragrunt.io/).
  If you do not have a particular version of terragrunt installed, `tgswitch` will download the version you desire.
  The installation is minimal and easy.
  Once installed, simply select the version you require from the dropdown and start using terragrunt.
architectures:
  - build-on: [amd64,arm64]
    run-on: [amd64,arm64]
assumes: [snapd2.45]
base: core18
 
grade: stable
confinement: strict

# plugs: //need snapcraft to make this work
#   home-bin:
#     interface: personal-files
#     read:
#     - $HOME/bin
#     write:
#     - $HOME/bin
 
apps:
  tgswitch:
    command: bin/tgswitch
    plugs:
      - home
      - network
      - network-bind
    #  - home-bin //need snapcraft to make this work

parts:
  tgswitch:
    source: .
    plugin: go
    go-importpath: github.com/Swahjak/terragrunt-switcher
    build-packages: [gcc, g++, make]
    go-buildtags:
      - tgswitch
    override-build: 
      VER=$(git ls-remote --tags git://github.com/Swahjak/terragrunt-switcher | awk '{print $2}'| awk -F"/" '{print $3}' | sort -n -t. -k1,1 -k2,2 -k3,3 | tail -n 2 | head -n1)
      go build  -v -ldflags "-X main.version=0.10.1010"  -o ../install/bin/tgswitch